### ISSUE TITLE
screenshot?

### ISSUE THREAD

**Issue by Shintaro-Miyazaki** [commoningtoys/Iris_Model#7]
A button, which makes a screenshot, which I can store on my machine.

**Comment by jazoza** [comment]
I would like to have an option to set "running time" for the model. It should be on the same screen as the rest of the initial setting (number of agents, minimal wage, model speed...) 
With this setting I could explore the different initial settings in a more systematic way, always comparing models after running for a specific amount of time. 
Next to this, @Shintaro-Miyazaki 's request for a screenshot button could be implemented as automatic if the "running time" is set - so if someone (e.g. myself) is using the model in the above described way, they can simply run it for e.g. 1 year and the model would automatically:
1. stop after one year
2. take a screenshot of itself
currently, I have to set an alarm for e.g. 2 minutes and take a screenshot (cmd+shift+4) manually.
The 1. option is more important to me (stopping after a set running time)

**Comment by Yyyyaaaannnnoooo** [comment]
added screenshot only for the viz / canvas. it is possible to set after how many months the model should stop.
