### ISSUE TITLE
visualisation: place of agent kind always shifting

### ISSUE THREAD

**Issue by jazoza** [commoningtoys/Iris_Model#9]
Each time the model is run, the order of different agent types on the screen changes. It would be better if these places would be fixed - so that they appear like in the menu:
______________________________
CURIOUS | PERFECTIONIST
___________|__________________
LAZY        | GOODWILLER
___________|__________________
<img width="1271" alt="2019-03-17-40agents-10each-maxcuriosity" src="https://user-images.githubusercontent.com/1549580/54740546-074e0800-4bbc-11e9-8b62-bfd06b7dd02e.png">
<img width="1267" alt="2019-03-17-40agents-37curious" src="https://user-images.githubusercontent.com/1549580/54740548-074e0800-4bbc-11e9-85ab-92a01b2c57e1.png">
<img width="1273" alt="2019-03-17-40agents-37goodwilled" src="https://user-images.githubusercontent.com/1549580/54740549-074e0800-4bbc-11e9-8ff6-40a08393f1da.png">
<img width="1266" alt="2019-03-20-40agents-10each-maxgoodwiledness" src="https://user-images.githubusercontent.com/1549580/54740550-07e69e80-4bbc-11e9-9088-213019bf3ab1.png">
<img width="1278" alt="2019-03-20-40agents-defaults" src="https://user-images.githubusercontent.com/1549580/54740552-07e69e80-4bbc-11e9-9555-03a1cc06a3b6.png">

**Comment by Yyyyaaaannnnoooo** [comment]
what do you exactly mean?

**Comment by Yyyyaaaannnnoooo** [comment]
Solved
